// Likert 1-6 labels used for all personality and academic mindset questions
const LIKERT_1_6 = {
  1: "Strongly disagree",
  2: "Disagree",
  3: "Slightly disagree",
  4: "Slightly agree",
  5: "Agree",
  6: "Strongly agree",
};

// Part 1: Academic Assessment
export const ACADEMIC_QUESTIONS = [
  {
    key: "year",
    category: "Academic",
    type: "singleSelect",
    question: "What year are you currently in?",
    options: ["1st year", "2nd year", "3rd year", "4th year", "4th+"],
  },
  {
    key: "gpa",
    category: "Academic",
    type: "singleSelect",
    question: "What's your current GPA?",
    options: [
      "4.0 – 3.5",
      "3.49 – 3.0",
      "2.99 – 2.5",
      "2.49 – 2.0",
      "Below 2.0",
      "First semester / No GPA yet",
    ],
  },
  {
    key: "study_start",
    category: "Academic",
    type: "singleSelect",
    question: "When do you usually start preparing for an exam?",
    options: [
      "2+ weeks before",
      "1–2 weeks before",
      "3–7 days before",
      "1–2 days before",
      "Night before",
    ],
  },
  {
    key: "work_approach",
    category: "Academic",
    type: "singleSelect",
    question: "How do you usually approach academic work?",
    options: [
      "Highly structured and perfection-oriented",
      "Balanced between structure and flexibility",
      "Flexible and outcome-focused",
    ],
  },
  {
    key: "time_pressure",
    category: "Academic",
    type: "singleSelect",
    question: "Which sounds more like you?",
    options: [
      "I like finishing things early so I can relax and clear my head",
      "I work best under pressure and enjoy the adrenaline of last-minute deadlines",
      "It depends on the task",
    ],
  },
  {
    key: "commitment_priority",
    category: "Academic",
    type: "singleSelect",
    question:
      "How much of your weekly energy goes to university compared to other commitments?",
    options: [
      "Most of my energy goes to university",
      "University is important, but balanced with other commitments",
      "University often competes with major life/work commitments",
    ],
  },
  {
    key: "commitment_reliability",
    category: "Academic",
    type: "singleSelect",
    question:
      "How often does university work get postponed because of life or other responsibilities?",
    options: ["Rarely", "Sometimes", "Often"],
  },
  {
    key: "study_effort",
    category: "Academic",
    type: "singleSelect",
    question: "How many hours do you usually study per week outside class?",
    options: [
      "0–5 hours",
      "5–10 hours",
      "10–20 hours",
      "20–30 hours",
      "30+ hours",
    ],
  },
  {
    key: "academic_mindset",
    category: "Academic",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    question:
      "I believe my abilities and intelligence can grow with effort and learning.",
  },
  {
    key: "working_style",
    category: "Academic",
    type: "singleSelect",
    question: "When studying or working with someone, what's your ideal style?",
    options: [
      "Work together most of the time",
      "Plan together, work independently",
      "Mostly independent, sync when needed",
    ],
  },
];

// Part 2: Personality Assessment (Big Five – Edited Version)
export const PERSONALITY_QUESTIONS = [
  {
    key: "ext_1",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    question: "I'm that person who makes friends everywhere they go.",
  },
  {
    key: "ext_2_rev",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    reverseScored: true,
    question: "Yeah… I'd choose going home over any party or event.",
  },
  {
    key: "cons_1",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    question: "I literally can't function if my space isn't clean.",
  },
  {
    key: "cons_2_rev",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    reverseScored: true,
    question:
      "Starting tasks is easy for me — finishing them is the tricky part.",
  },
  {
    key: "agr_1",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    question: "I care about other people's feelings and try to help them.",
  },
  {
    key: "agr_2_rev",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    reverseScored: true,
    question: "I am not very interested in other people's problems.",
  },
  {
    key: "neu_1_rev",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    reverseScored: true,
    question: "I'm usually calm — some people even call me 'cold.'",
  },
  {
    key: "neu_2",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    question: "I carry way too much mental weight stressing about stuff.",
  },
  {
    key: "opn_1",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    question: "I like learning new things and trying different experiences.",
  },
  {
    key: "opn_2_rev",
    category: "Personality",
    type: "likert",
    min: 1,
    max: 6,
    labels: LIKERT_1_6,
    reverseScored: true,
    question: "I like sticking to a routine — change usually messes with me.",
  },
];

export const ALL_QUESTIONS = [...ACADEMIC_QUESTIONS, ...PERSONALITY_QUESTIONS];
