export const ACADEMIC_QUESTIONS = [
  {
    key: "year",
    category: "Academic DNA",
    type: "singleSelect",
    question: "Which year of study are you currently in?",
    options: ["First Year", "Second Year", "Third Year", "Fourth Year", "Graduate"],
  },
  {
    key: "gpa",
    category: "Academic DNA",
    type: "singleSelect",
    question: "How would you describe your current GPA band?",
    options: ["3.7 - 4.0", "3.3 - 3.69", "3.0 - 3.29", "Below 3.0", "Prefer not to say"],
  },
  {
    key: "study_rhythm",
    category: "Academic DNA",
    type: "singleSelect",
    question: "What study rhythm feels most natural for you?",
    options: [
      "Deep focus sprints",
      "Consistent daily cadence",
      "Deadline-powered bursts",
      "Collaborative sessions",
    ],
  },
  {
    key: "course_load",
    category: "Academic DNA",
    type: "singleSelect",
    question: "How intense is your current course load?",
    options: ["Light", "Balanced", "Demanding", "Relentless"],
  },
  {
    key: "research_interest",
    category: "Academic DNA",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Hands-on projects",
      4: "Mix of both",
      7: "Deep research",
    },
    question: "I get energised by exploring complex research problems over hands-on builds.",
  },
  {
    key: "deadline_habits",
    category: "Academic DNA",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Ahead of time",
      4: "Flexible",
      7: "Last-minute rush",
    },
    question: "I typically finalise coursework right before the deadline.",
    reverseScored: true,
  },
  {
    key: "collab_preference",
    category: "Academic DNA",
    type: "singleSelect",
    question: "When teaming up for coursework, what do you value most?",
    options: [
      "Clear roles & structure",
      "Creative brainstorming",
      "Fast execution",
      "Mentorship & learning",
    ],
  },
  {
    key: "feedback_style",
    category: "Academic DNA",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Prefer private reflection",
      4: "Depends on context",
      7: "Prefer open debate",
    },
    question: "I enjoy open critique sessions to polish academic work.",
  },
];

export const PERSONALITY_QUESTIONS = [
  {
    key: "ext_1",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Quiet anchor",
      4: "Selective connector",
      7: "Social spark",
    },
    question: "I naturally spark energy in group settings.",
  },
  {
    key: "ext_2",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Recharge solo",
      4: "Depends on the vibe",
      7: "Recharge with people",
    },
    question: "I feel drained after extended group collaboration.",
    reverseScored: true,
  },
  {
    key: "agr_1",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Challenger",
      4: "Diplomatic",
      7: "Empathetic guide",
    },
    question: "I intuitively read the emotional climate of a team.",
  },
  {
    key: "agr_2",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Direct feedback",
      4: "Contextual",
      7: "Soft delivery",
    },
    question: "I soften my feedback to keep harmony within the group.",
  },
  {
    key: "cons_1",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Play it loose",
      4: "Adaptive planner",
      7: "Precision planner",
    },
    question: "I create detailed plans before kicking off projects.",
  },
  {
    key: "cons_2",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Thrives in chaos",
      4: "Flexible",
      7: "Needs structure",
    },
    question: "Unexpected changes to plans easily throw me off balance.",
    reverseScored: true,
  },
  {
    key: "opn_1",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Grounded",
      4: "Curious",
      7: "Visionary",
    },
    question: "I get excited exploring wild ideas that others might call unrealistic.",
  },
  {
    key: "opn_2",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Prefer reference",
      4: "Mix of both",
      7: "Prefer abstraction",
    },
    question: "I learn best through abstract concepts over concrete examples.",
  },
  {
    key: "ner_1",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Steady",
      4: "Occasionally tense",
      7: "Easily stressed",
    },
    question: "I stay calm even when deadlines stack up.",
    reverseScored: true,
  },
  {
    key: "ner_2",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Recover quickly",
      4: "Need short breaks",
      7: "Need long resets",
    },
    question: "It takes me a long time to bounce back after high-pressure pushes.",
    reverseScored: true,
  },
  {
    key: "ldr_1",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Support role",
      4: "Situational",
      7: "Lead instinctively",
    },
    question: "I naturally take the reins when a team lacks direction.",
  },
  {
    key: "ldr_2",
    category: "Personality Pulse",
    type: "likert",
    min: 1,
    max: 7,
    labels: {
      1: "Prefer consensus",
      4: "Balance both",
      7: "Decide quickly",
    },
    question: "I am comfortable making fast decisions with limited data.",
  },
];

export const ALL_QUESTIONS = [...ACADEMIC_QUESTIONS, ...PERSONALITY_QUESTIONS];
